name: pc_build
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^0.5.1
  flutter_cache_store: ^0.4.0
  flutter_range_slider: ^1.1.0
  shared_preferences: ^0.4.0
  flutter_money_formatter: ^0.7.3
  # flutter_webview_plugin: ^0.3.3
  rxdart: ^0.21.0
  get_it: ^1.0.3
  bloc: ^0.11.0
  flutter_bloc: ^0.9.0
  equatable: ^0.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
