name: pc_build
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cached_network_image: ^0.5.1
  # flutter_cache_store: ^0.7.2
  http:
  flutter_range_slider: 
  shared_preferences: 
  flutter_money_formatter: 
  webview_flutter: 
  rxdart: 
  get_it: 
  bloc: 
  flutter_bloc: 
  equatable: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
